
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usman_Aslam
 */
public class LoginForm extends javax.swing.JFrame {

    
    Connection conn;
    Statement st; 
    PreparedStatement pst;
    ResultSet rs;
    
   
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        conn = MyConnection.getConnection();
        try {
            st = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        user_lbl.setVisible(false);
        pass_lbl.setVisible(false);
        
        user_tf.setCaretPosition(0);
        

    }
    public int getCount(String tblName)
    {
        int total = 0;
        String qurrey = "select * from " + tblName;
        try {
            rs = st.executeQuery(qurrey);
            while(rs.next())
            {
                 total++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        user_tf = new javax.swing.JTextField();
        pass_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pass_tf = new javax.swing.JPasswordField();
        user_lbl = new javax.swing.JLabel();
        SignInBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user_validity_lbl = new javax.swing.JLabel();
        pass_validity_lbl = new javax.swing.JLabel();
        Forgot_pass_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login_Form");
        setLocationByPlatform(true);

        Jpanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("UserName:");

        user_tf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        user_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tfMouseClicked(evt);
            }
        });
        user_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_tfActionPerformed(evt);
            }
        });
        user_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_tfKeyPressed(evt);
            }
        });

        pass_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pass_lbl.setForeground(new java.awt.Color(255, 0, 51));
        pass_lbl.setText("*");
        pass_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Password:");

        user_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        user_lbl.setForeground(new java.awt.Color(255, 0, 51));
        user_lbl.setText("*");
        user_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        SignInBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(51, 102, 255));
        SignInBtn.setText("SignIn");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(51, 102, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 204));
        jLabel4.setText(" ADU Management System");

        user_validity_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        user_validity_lbl.setForeground(new java.awt.Color(255, 0, 0));
        user_validity_lbl.setText(" ");
        user_validity_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        pass_validity_lbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pass_validity_lbl.setForeground(new java.awt.Color(255, 0, 0));
        pass_validity_lbl.setText(" ");
        pass_validity_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Forgot_pass_lbl.setFont(new java.awt.Font("Segoe UI Symbol", 0, 10)); // NOI18N
        Forgot_pass_lbl.setForeground(new java.awt.Color(0, 0, 255));
        Forgot_pass_lbl.setText("Forgot Your Password ?");
        Forgot_pass_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Forgot_pass_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Jpanel1Layout = new javax.swing.GroupLayout(Jpanel1);
        Jpanel1.setLayout(Jpanel1Layout);
        Jpanel1Layout.setHorizontalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass_validity_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forgot_pass_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(user_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_validity_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_lbl)
                            .addComponent(pass_lbl))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel1Layout.createSequentialGroup()
                        .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Jpanel1Layout.createSequentialGroup()
                                .addComponent(SignInBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginBtn))
                            .addGroup(Jpanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))
                        .addGap(62, 62, 62))))
        );
        Jpanel1Layout.setVerticalGroup(
            Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(64, 64, 64)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(user_validity_lbl))
                    .addGroup(Jpanel1Layout.createSequentialGroup()
                        .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pass_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Jpanel1Layout.createSequentialGroup()
                                .addComponent(user_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(pass_lbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_validity_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Forgot_pass_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(Jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(SignInBtn))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        user_lbl.setVisible(false);
        pass_lbl.setVisible(false);
        pass_validity_lbl.setText(" ");
        user_validity_lbl.setText(" ");
        
        
        if(user_tf.getText().equals(""))
            user_lbl.setVisible(true);
        if(pass_tf.getText().equals(""))
        {
            pass_lbl.setVisible(true);
        }
        else
        {
            String user = user_tf.getText();
            String pass = pass_tf.getText();
            
            String qurrey = "select UserName,Password from User where UserName = '"+
                              user+"'";
            try 
            {
                rs = st.executeQuery(qurrey);
                
                if(rs.next())
                {
                    if(rs.getString("Password").equals(pass))
                    {
                        System.out.println("yes");
                        MainWindowForm mWf = new MainWindowForm();
                        mWf.setVisible(true);
                        mWf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        this.dispose();
                    }
                    else
                        pass_validity_lbl.setText(" Invalid Password");
                }
                else
                    user_validity_lbl.setText(" Invalid User Name");
                    
                
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        user_lbl.setVisible(false);
        pass_lbl.setVisible(false);
        
        
        if(user_tf.getText().equals(""))
            user_lbl.setVisible(true);
        if(pass_tf.getText().equals(""))
        {
            pass_lbl.setVisible(true);
            System.out.println("Press");
        }
        else
        {
            String user = user_tf.getText();
            String pass = pass_tf.getText();
            
            String qurrey = "select UserName from User where UserName = '" + user + "'";
            try 
            {
                rs = st.executeQuery(qurrey);
                
                if(rs.next())
                {
                    System.out.println("yes");
                    JOptionPane.showMessageDialog(null,"This UserName is Already Exits..", "Alert", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    System.out.println("No");
                    qurrey = "insert into User (UserName,Password) values (?,?)";
                    pst = conn.prepareStatement(qurrey);
                    
                    pst.setString(1,user);
                    pst.setString(2,pass);
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null,"Your Account is Registered Now.\nWelcome to ADU Management System.");
                    MainWindowForm mWf = new MainWindowForm();
                    mWf.setVisible(true);
                    mWf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();
                }
                
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void user_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_tfActionPerformed

    private void user_tfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tfMouseClicked
    
    }//GEN-LAST:event_user_tfMouseClicked

    private void user_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_tfKeyPressed

    }//GEN-LAST:event_user_tfKeyPressed

    private void Forgot_pass_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Forgot_pass_lblMouseClicked
        if(user_tf.getText().equals(""))
            user_lbl.setVisible(true);
        else
        {
           String user = user_tf.getText();
           String pass ;
            
            String qurrey = "select UserName from User where UserName = '" + user + "'";
            try 
            {
                rs = st.executeQuery(qurrey);
                
                if(rs.next())
                {
                    System.out.println("yes");
                    pass = JOptionPane.showInputDialog(null,"Enter New Password");
                   
                    qurrey = "update User Set Password = ? where Username = ?";
                    pst = conn.prepareStatement(qurrey);
                    
                    pst.setString(1,pass);
                    pst.setString(2,user);
                    
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null,"Successfully Your Password is Change.");
                    MainWindowForm mWf = new MainWindowForm();
                    mWf.setVisible(true);
                    mWf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.dispose();
                }
                else
                {
                    System.out.println("No");
                    
                }
                
                
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            
        }
    }//GEN-LAST:event_Forgot_pass_lblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Forgot_pass_lbl;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel pass_lbl;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JLabel pass_validity_lbl;
    private javax.swing.JLabel user_lbl;
    private javax.swing.JTextField user_tf;
    private javax.swing.JLabel user_validity_lbl;
    // End of variables declaration//GEN-END:variables
}
